/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.dv8tion.jda)
    api(libs.io.github.cdimascio.dotenv.java)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.ch.qos.logback.logback.classic)
    testImplementation(libs.junit.junit)
}

group = "com.dislang"
version = "1.0-SNAPSHOT"
description = "dislang"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
